### ISSUE TITLE
Android 11（小米11）运行微信报错提示找不到Ljunit/framework/Assert;

### ISSUE THREAD

**Issue by 80945540** [2-young-2-simple/VirtualApp#10]
java.lang.RuntimeException: Unable to instantiate application com.tencent.mm.app.Application: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Failed resolution of: Ljunit/framework/Assert;

**Comment by lianglixin** [comment]
克隆即可

**Comment by twoways** [comment]
> java.lang.RuntimeException: Unable to instantiate application com.tencent.mm.app.Application: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Failed resolution of: Ljunit/framework/Assert;

你好，请问这个问题解决了吗？

**Comment by lianglixin** [comment]
> > java.lang.RuntimeException: Unable to instantiate application com.tencent.mm.app.Application: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Failed resolution of: Ljunit/framework/Assert;
> 
> 你好，请问这个问题解决了吗？

克隆即可，建议使用新的商业版（QQ384550791）
