### ISSUE TITLE
Android11错误

### ISSUE THREAD

**Issue by Tokyonth** [2-young-2-simple/VirtualApp#17]
Android11 MIUI12.5
点击软件内克隆的APP无反应
ProviderHook.java  ->
Object invoke() -> Bundle extras = (Bundle) args[start + 2];
报ClassCastException: java.lang.String cannot be cast to android.os.Bundle

**Comment by lianglixin** [comment]
ProviderHook.java里面的 invoke 直接 注释掉 methodBox后面的，改成 return methodBox.call();即可
