### ISSUE TITLE
出现这个错误是因为NDK版本问题吗？

### ISSUE THREAD

**Issue by sd3970566** [2-young-2-simple/VirtualApp#25]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\Users\Administrator\AppData\Local\Android\sdk\ndk\21.3.6528147\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\huoshan_Project\VirtualApp-master\VirtualApp\lib\src\main\jni\Android.mk NDK_APPLICATION_MK=E:\huoshan_Project\VirtualApp-master\VirtualApp\lib\src\main\jni\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=E:/huoshan_Project/VirtualApp-master/VirtualApp/lib/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=E:\huoshan_Project\VirtualApp-master\VirtualApp\lib\build\intermediates\ndkBuild\debug\lib E:/huoshan_Project/VirtualApp-master/VirtualApp/lib/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/libv++_64.so}
  Android NDK: WARNING: Ignoring unknown import directory: :E:/huoshan_Project/VirtualApp-master/VirtualApp/lib/src/main/jni    
  Android NDK: WARNING:E:\huoshan_Project\VirtualApp-master\VirtualApp\lib\src\main\jni\Android.mk:v++_64: non-system libraries in linker flags: -latomic    
  Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
  Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
  Android NDK:     current module    
  [arm64-v8a] Compile++      : v++_64 <= safekey_jni.cpp
  In file included from E:/huoshan_Project/VirtualApp-master/VirtualApp/lib/src/main/jni/safekey/safekey_jni.cpp:8:
  In file included from C:/Users/Administrator/AppData/Local/Android/sdk/ndk/21.3.6528147/build//../sources/cxx-stl/llvm-libc++/include\stdlib.h:100:
  C:/Users/Administrator/AppData/Local/Android/sdk/ndk/21.3.6528147/build//../sources/cxx-stl/llvm-libc++/include\math.h:996:66: error: expected unqualified-id
  inline _LIBCPP_INLINE_VISIBILITY float       log(float __lcpp_x) _NOEXCEPT       {return ::logf(__lcpp_x);}
                                                                   ^
  C:/Users/Administrator/AppData/Local/Android/sdk/ndk/21.3.6528147/build//../sources/cxx-stl/llvm-libc++/include\__config:778:21: note: expanded from macro '_NOEXCEPT'
  #  define _NOEXCEPT noexcept
                      ^
  In file included from E:/huoshan_Project/VirtualApp-master/VirtualApp/lib/src/main/jni/safekey/safekey_jni.cpp:8:
  In file included from C:/Users/Administrator/AppData/Local/Android/sdk/ndk/21.3.6528147/build//../sources/cxx-stl/llvm-libc++/include\stdlib.h:100:
  C:/Users/Administrator/AppData/Local/Android/sdk/ndk/21.3.6528147/build//../sources/cxx-stl/llvm-libc++/include\math.h:997:72: error: expected unqualified-id
  inline _LIBCPP_INLINE_VISIBILITY long double log(long double __lcpp_x) _NOEXCEPT {return ::logl(__lcpp_x);}
                                                                         ^
  C:/Users/Administrator/AppData/Local/Android/sdk/ndk/21.3.6528147/build//../sources/cxx-stl/llvm-libc++/include\__config:778:21: note: expanded from macro '_NOEXCEPT'
  #  define _NOEXCEPT noexcept
                      ^
  In file included from E:/huoshan_Project/VirtualApp-master/VirtualApp/lib/src/main/jni/safekey/safekey_jni.cpp:8:
  In file included from C:/Users/Administrator/AppData/Local/Android/sdk/ndk/21.3.6528147/build//../sources/cxx-stl/llvm-libc++/include\stdlib.h:100:
  C:/Users/Administrator/AppData/Local/Android/sdk/ndk/21.3.6528147/build//../sources/cxx-stl/llvm-libc++/include\math.h:1003:19: error: expected unqualified-id
  log(_A1 __lcpp_x) _NOEXCEPT {return ::log((double)__lcpp_x);}
                    ^
  C:/Users/Administrator/AppData/Local/Android/sdk/ndk/21.3.6528147/build//../sources/cxx-stl/llvm-libc++/include\__config:778:21: note: expanded from macro '_NOEXCEPT'
  #  define _NOEXCEPT noexcept
                      ^
  3 errors generated.
  make: *** [C:/Users/Administrator/AppData/Local/Android/sdk/ndk/21.3.6528147/build//../build/core/build-binary.mk:478: E:/huoshan_Project/VirtualApp-master/VirtualApp/lib/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs/v++_64/safekey/safekey_jni.o] Error 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

**Comment by lianglixin** [comment]
编译器版本太老了，此外建议删掉 safekey_jni 相关的文件进行编译。
这个错误的原因是无法编译
https://github.com/2-young-2-simple/VirtualApp/tree/master/VirtualApp/lib/src/main/jni/utils
这个文件夹下的文件，实际上可以删掉safekey_jni相关的内容再进行编译（如果仍要使用当前版本的编译器的话）

**Comment by lihe07** [comment]
我也遇到了相同的问题，我使用的NDK版本是`21.4.7075529`
我的解决方法是找到这个文件：`\Android\ndk\21.4.7075529\sources\cxx-stl\llvm-libc++\include\stdlib.h`
找到第100行的 `#include <math.h>` 将其注释掉
（这一操作可以让VA编译通过，但是会影响到其他项目，所以记得在用完后改回来）
