### ISSUE TITLE
跑在原系统的app流程，跑到虚拟app卡，卡ui这种，掉帧，有时候ANR

### ISSUE THREAD

**Issue by albertPu** [2-young-2-simple/VirtualApp#27]

**Comment by albertPu** [comment]
@lianglixin

**Comment by lianglixin** [comment]
1、由于系统服务的代理，所以内部应用必定有性能损耗，性能损耗跟手机单核主频有关，单核主频越高性能百分比损耗越少。
2、卡住可以看看日志，一般来说也仅仅是需要等待一会，如果ANR有可能是崩溃等异常
3、可以根据应用定制优化方案，有的应用可以通过精简内部组件代码等等优化运行速度
