### ISSUE TITLE
文件重定向学习 无法调适 

### ISSUE THREAD

**Issue by jy03236862** [2-young-2-simple/VirtualApp#28]
Cannot find module that matches process name com.xxx.xx. 请问需要修改哪里可以动态调试这一部分代码 非常感谢！

**Comment by jy03236862** [comment]
可能说得不够具体 就是 使用Android studio 调适 VA 的时候 断点 文件重定向的代码 无法 attach 到进程中...

**Comment by lianglixin** [comment]
以下两个函数调用
mirror.android.os.Process.setArgV0.call(processName);
DdmHandleAppNameJBMR1.setAppName.call(processName, 0);
设置了进程名，实际上进程名是包名:p0或者包名:p1一类的。
只是AS里面进程名显示的是设置以后的进程名，实际上进程名，系统里面认的不是这个。
例如SandVXposed是 io.virtualapp.sandvxposed:p0

**Comment by jy03236862** [comment]
非常感谢大佬！
