### ISSUE TITLE
关于文件重定向的一些问题

### ISSUE THREAD

**Issue by jy03236862** [2-young-2-simple/VirtualApp#30]
VA 在做文件重定向的时候 将很多linux的方法 比如 linkat mkdirat等 的path重定向了 这些很好理解 
有个不太好理解的是 为什么VA 还要自己搞一套和 fd 文件句柄相关的系统  请大佬稍微回答一下 谢谢啦~

**Comment by lianglixin** [comment]
利用文件句柄可以反查真实文件，所以需要重定向这一部分。
另外这一套开源的版本不止有文件重定向，还有为了企业安全设计的安全文件管理空间功能
因此会内置一些企业安全相关的逻辑。
