### ISSUE TITLE
[学习]关于文件重定向的问题

### ISSUE THREAD

**Issue by jy03236862** [2-young-2-simple/VirtualApp#32]
文件重定向里面的 有一个 myfile.so😭引入 想知道这个动态库的源码大佬有么???  直接调用有一点看不懂动态库里面的逻辑 非常感谢！

**Comment by lianglixin** [comment]
这个是跟企业安全有关的，可以不需要，具体参考：
[此处](https://github.com/lianglixin/SandVXposed/blob/master/lib/src/main/jni/Foundation/IOUniformer.cpp)
逻辑也比较简单，使用的是Substrate，如果有兴趣可以换成自己的内联hook框架，具体参考：
[此处](https://github.com/lianglixin/EdXposed/blob/master/edxp-core/src/main/cpp/main/src/fox_inlineHook.cpp)
