### ISSUE TITLE
编译不了，缺少类

### ISSUE THREAD

**Issue by lishangwl** [2-young-2-simple/VirtualApp#33]
com.android.dx

import com.android.dx.rop.code.Rop;
import com.android.dx.rop.code.Rops;
import com.android.dx.rop.type.TypeList;

SandVXposed-master\lib\src\main\java\com\android\dx\Label.java:21: 错误: 程序包com.android.dx.rop.code不存在
import com.android.dx.rop.code.InsnList;

少很多com.android.dx包下的类
                              ^

**Comment by lianglixin** [comment]
[自行查看](https://android.googlesource.com/platform/dalvik/+log/master/dx)
