### ISSUE TITLE
启动应用Hook 在MyComponentDelegate内操作SD卡文件异常

### ISSUE THREAD

**Issue by jinmaotowne** [2-young-2-simple/VirtualApp#6]
启动应用Hook 在MyComponentDelegate->beforeApplicationCreate内 读取文件（open failed: ENOENT (No such file or directory)）或者操作数据库（unknown error (code 14 SQLITE_CANTOPEN): Could not open database）均提示异常

**Comment by lianglixin** [comment]
内部文件有隔离，数据文件应放置到
/data/data/你的沙盒包名/
这个目录下
